import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Heder from '@/components/Heder';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
      <div className="w-full flex text-center justify-center relative">
      <Heder></Heder>
      </div>
        {children}
        </body>
    </html>
  );
}
